clean: FORCE
	g++ -o main main.cpp piano_chord.cpp piano_chord.h piano_chord_specific.h piano_chord_specific.cpp song_data.h song_data.cpp song_list.cpp song_list_entry.cpp song_list_entry.h song_list.h song_list_observer.cpp song_list_observer.h
	./main < input.txt
FORCE:
